---
name: Molecule Test

"on":
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

defaults:
  run:
    working-directory: "arpanrec.server_workspace"

jobs:
  molecule_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          path: "arpanrec.server_workspace"

      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel setuptools
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test
        run: |
          molecule test
