---
- name: Own CA
  hosts: localhost
  become: false
  gather_facts: true
  vars_files: "{{ playbook_dir }}/vars/main.yml"
  vars:
    - own_ca_debug_no_log: false
  tasks:
    - name: OpenSSH | arpanrec | Import Passwords
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/vars/passwords.yml"
      ignore_errors: true

    - name: OpenSSH | arpanrec | Check for passphrase
      ansible.builtin.fail:
        msg: openssh_arpanrec_passphrase is missing
      when: >
        openssh_arpanrec_passphrase is undefined
        or
        openssh_arpanrec_passphrase == None
        or
        (( openssh_arpanrec_passphrase | length ) < 1)

    - name: OpenSSH | arpanrec | Create Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0700"
      with_items:
        - "{{ openssh_arpanrec_generated_resources_dir }}"
        - "{{ files_dir }}"

    - name: OpenSSH | arpanrec | Generate an OpenSSH keypair
      community.crypto.openssh_keypair:
        path: "{{ openssh_arpanrec_key_file }}"
        mode: "0400"
        type: "ecdsa"
        comment: me@arpanrec.com
        private_key_format: auto
        passphrase: "{{ openssh_arpanrec_passphrase }}"
      register: openssh_keypair_result

    - name: OpenSSH | arpanrec | SSH Keys Details
      ansible.builtin.debug:
        var: openssh_keypair_result
